### ISSUE TITLE
MWE showing different pattern

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/csl-json#3]
Dear @neeleshb 
All other dictionaries had two kind of dict object.

First connects the headword to a bunch of ids like `"adrift": "313,31810"`

The second connects the id to entry like
```
            "313": "<BR>ADRIFT , adv. इतस्ततः प्लवमानः -ना -नं.",
            "31810": "<BR>ADRIFT , a. or adv. प्रवाहाधीनः -ना -नं, ओघाधीनः -ना -नं.",
```

Whereas in Monier Williams English-Sanskrit dictionary, there seems to be a combined entry like the following.
```
        "adrift": [
            "<BR>ADRIFT , adv. इतस्ततः प्लवमानः -ना -नं.",
            "<BR>ADRIFT , a. or adv. प्रवाहाधीनः -ना -नं, ओघाधीनः -ना -नं."
        ],
```

Is it OK if I keep MWE also in the same manner as the rest of the dictionaries are?
```

**Comment by neeleshb** [comment]
yes it is ok to keep MWE in same manner as others.
