### ISSUE TITLE
All dictionaries of Cologne in json format

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/csl-json#4]
https://github.com/sanskrit-lexicon/csl-json/tree/main/ashtadhyayi.com

@neeleshb

These are all dictionaries of Cologne except Apte1957 and Pune dictionary (due to copyright issues).
The data is made as per the format of files that you sent.

You may examine the possibility / reasonablility of integrating them in ashtadhyayi.com website and also in the android and ios applications.

Kindly let me know if you run into any difficulty in the process.

**Comment by neeleshb** [comment]
Thank you. I see that there are a bunch of json files with shorthand names.
Is it possible to give the full names for each of them which can be used to
display the dictionary name on the website.

I should be able to try these and make a change on my side in a few days. I
will keep you updated.

Also, is this going to be auto-refreshed whenever you make a change?

Finally please send me the exact statement to be put under the 'credits'
section.

**Comment by drdhaval2785** [comment]
1. https://www.sanskrit-lexicon.uni-koeln.de/index.html  First column is the shorthand and the third one is the popular name of the dictionary.
2. This is not going to be auto-refreshed when we make a change. It is still in manual mode. 
3. I will put the statement to be put under the 'credits' section after consulting with @funderburkjim who has been maintaining these dictionaries for many years.

**Comment by drdhaval2785** [comment]
Now it is auto updated. 
Credits being tracked in separate issue mentioned above. 
Closing this issue.
