### ISSUE TITLE
auto-sync on ashtadhyayi.com

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/csl-json#5]
https://github.com/sanskrit-lexicon/csl-json/commit/b1082c372f852e107a5b5d1abbd2eae8910db007 made a change to SKD
श्वाश्व्ः -> श्वाश्वः
Glad to see that the same was carried forward (maybe by some auto-syncing) to ashtadhyayi.com. 
This in effect means that ashtadhyayi.com would be auto-updated based on changes in this github repository.
Thank you @neeleshb

**Comment by drdhaval2785** [comment]
Can you explain the frequency or modality of updation once a change is made to csl-json repository?

**Comment by neeleshb** [comment]
It should be real time.  The website reads directly from the csl-json
repository. There is no middle script running (at least right now).
However, clients cache the old copy and use it while the new copy is
fetched in the background. So it may take a few clicks on the website
before the client gets the new copy.
If you try it in incognito mode then it should be immediate.

**Comment by drdhaval2785** [comment]
Great to know that it is realtime.

**Comment by gasyoun** [comment]
> This in effect means that ashtadhyayi.com would be auto-updated based on changes in this github repository.

You mean the Cologne repository, well done, guys.
