### ISSUE TITLE
mw.json empty after latest commit (8add17b) and words still in SLP1

### ISSUE THREAD

**Issue by tempapy** [sanskrit-lexicon/csl-json#7]
Hello,

The mw.json file only has 8 lines in the latest commit (8add17b). 
Also, in the previous commit (85ac571), many words are still in SLP1 in their definitions, for example aMSAMSa, aMSAMsi, aMSAvataraRa (keys 43, 44, 45)

Sorry if I am writing in the wrong place, I'm not familiar with github.
Thank you

**Comment by drdhaval2785** [comment]
Thank you for your bug report. I am aware about the issue and will be resolving the issue in a week or so. Sorry for the inconvenience.

**Comment by ganarajpr** [comment]
Dhaval great work btw. The mw.json is currently empty still. Is that something that can be fixed ? Or is it something I can help fix ?

**Comment by drdhaval2785** [comment]
This should be resolved now.
I reverted the commits that caused the problem.

**Comment by drdhaval2785** [comment]
Closing this issue. 
Reopen if needed.
